name: Build

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the environment to deploy to (dev, qa, prod)'
        required: true
        default: 'qa'
        type: choice
        options:
          - dev
          - qa
          - prod

jobs:
  build_android:
    name: Build Android 
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Copy Secret Files
        env:
          ENV_BASE64: ${{ secrets.ENV }}
        run: |
          ENV_FILE="$RUNNER_TEMP/.env"
          echo -n "$ENV_BASE64" | base64 --decode > $ENV_FILE
          echo "Environment file created from ${{ github.event.inputs.environment }}"
          cp $ENV_FILE $GITHUB_WORKSPACE/.env 

      - name: Verify .env File
        run: |
          if [ -f .env ]; then
            echo ".env file exists!"
          else
            echo ".env file is missing!"
            exit 1
          fi

      - name: Update Build Number (Version Code)
        run: |
          FILE=android/app/build.gradle
          VERSION_CODE=$(grep -oP 'versionCode \K\d+' $FILE)
          NEW_VERSION_CODE=$((VERSION_CODE + 1))
          sed -i "s/versionCode $VERSION_CODE/versionCode $NEW_VERSION_CODE/g" $FILE

      - name: Build Release APK
        run: |
          cd android
          export ENVFILE=../.env
          ./gradlew assembleRelease

      - name: Sign APK
        uses: upup-company/apksigner-android@v1
        id: sign_app
        with:
          releaseDirectory: android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE }}
          alias: ${{ secrets.RELEASE_KEYSTORE_ALIAS }}
          keyStorePassword: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.RELEASE_KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Verify APK Path
        run: |
          echo "APK Path: ${{ steps.sign_app.outputs.signedReleaseFile }}"

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-release-apk
          path: ${{ steps.sign_app.outputs.signedReleaseFile }}

  build_ios:
    name: Build iOS 
    runs-on: macos-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Copy Secret Files
        env:
          ENV_BASE64: ${{ secrets.ENV }}
        run: |
          ENV_FILE="$RUNNER_TEMP/.env"
          echo -n "$ENV_BASE64" | base64 --decode > $ENV_FILE
          echo "Environment file created from ${{ github.event.inputs.environment }}"
          cp $ENV_FILE $GITHUB_WORKSPACE/.env 

      - name: Verify .env File
        run: |
          if [ -f .env ]; then
            echo ".env file exists!"
          else
            echo ".env file is missing!"
            exit 1
          fi

      - name: Install iOS Distribution Certificate
        env:
          CERTIFICATE_BASE64: ${{ secrets.IOS_DISTRIBUTION_CERTIFICATE }}
          CERTIFICATE_PASSWORD: ${{ secrets.IOS_DISTRIBUTION_CERTIFICATE_PASSWORD }}
        run: |
          echo "$CERTIFICATE_BASE64" | base64 --decode > ios_certificate.p12
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import ios_certificate.p12 -k build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain

      - name: Install Provisioning Profile
        env:
          PROFILE_BASE64: ${{ secrets.IOS_ADHOC_PROFILE }}
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "$PROFILE_BASE64" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision

      - name: Build iOS App
        run: |
          xcodebuild -workspace ios/react_native.xcworkspace \
                     -scheme react_native \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath build/react_native.xcarchive \
                     archive

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
                     -archivePath build/react_native.xcarchive \
                     -exportOptionsPlist ios/exportOptions.plist \
                     -exportPath build

      - name: Upload IPA as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-release-ipa
          path: build/react_native.ipa
