name: Build

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the environment to deploy to (dev, qa, prod)'
        required: true
        default: 'qa'
        type: choice
        options:
          - dev
          - qa
          - prod
      
      platform:
        description: 'Select platform to build (android, ios, both)'
        required: true
        default: 'both'
        type: choice
        options:
          - android
          - ios
          - both

jobs:
  build_android:
    name: Build Android 
    runs-on: ubuntu-latest
    if: github.event.inputs.platform == 'android' || github.event.inputs.platform == 'both'
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4


      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"


      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"


      - name: Install Dependencies
        run: yarn install --immutable


      - name: Copy Environment Secret Files  
        env:
          ENV_BASE64: ${{ secrets.ENV }}
        run: |
          ENV_FILE="$RUNNER_TEMP/.env"
          echo -n "$ENV_BASE64" | base64 --decode > $ENV_FILE
          echo "Environment file created from ${{ github.event.inputs.environment }}"
          cp $ENV_FILE $GITHUB_WORKSPACE/.env 
          

      - name: Verify .env File
        run: |
          if [ -f .env ]; then
            echo ".env file exists!"
          else
            echo ".env file is missing!"
            exit 1
          fi

      - name: Generate Unique Build Number
        id: build_number
        run: |
          DATE=$(date +'%d%m%y')
          INCREMENTAL_NUMBER=$(printf "%02d" ${{ github.run_number }})
          BUILD_NUMBER="${DATE}${INCREMENTAL_NUMBER}"
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV


      - name: Update Android Version Code
        run: |
          sed -i "s/versionCode [0-9]\+/versionCode $BUILD_NUMBER/" android/app/build.gradle


      - name: Build APK
        run: |
          cd android
          export ENVFILE=../.env
          ./gradlew assembleRelease


      - name: Sign APK
        uses: upup-company/apksigner-android@v1
        id: sign_app
        with:
          releaseDirectory: android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE }}
          alias: ${{ secrets.RELEASE_KEYSTORE_ALIAS }}
          keyStorePassword: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.RELEASE_KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"


      - name: Verify APK Path
        run: |
          echo "APK Path: ${{ steps.sign_app.outputs.signedReleaseFile }}"


      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-release-apk
          path: ${{ steps.sign_app.outputs.signedReleaseFile }}

  build_ios:
    name: Build iOS 
    runs-on: macos-latest
    if: github.event.inputs.platform == 'ios' || github.event.inputs.platform == 'both'
    environment: ${{ github.event.inputs.environment }}


    steps:
      - name: Checkout Code
        uses: actions/checkout@v4


      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"


      - name: Install Dependencies
        run: yarn install --immutable


      - name: Install Pods
        run: cd ios && pod install --repo-update


      - name: Copy Environment Secret Files
        env:
          ENV_BASE64: ${{ secrets.ENV }}
        run: |
          ENV_FILE="$RUNNER_TEMP/.env"
          echo -n "$ENV_BASE64" | base64 --decode > $ENV_FILE
          echo "Environment file created from ${{ github.event.inputs.environment }}"
          cp $ENV_FILE $GITHUB_WORKSPACE/.env 

          
      - name: Verify .env File
        run: |
          if [ -f .env ]; then
          echo ".env file exists!"
          else
          echo ".env file is missing!"
          exit 1
          fi
          

      - name: Generate Unique Build Number
        id: build_number
        run: |
          DATE=$(date +'%d%m%y')
          INCREMENTAL_NUMBER=$(printf "%02d" ${{ github.run_number }})
          BUILD_NUMBER="${DATE}${INCREMENTAL_NUMBER}"
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV

          
      - name: Update iOS Build Number
        run: |
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" ios/react_native/Info.plist


      - name: Install iOS Distribution Certificate
        env:
          CERTIFICATE_BASE64: ${{ secrets.IOS_DISTRIBUTION_CERTIFICATE }}
          CERTIFICATE_PASSWORD: ${{ secrets.IOS_DISTRIBUTION_CERTIFICATE_PASSWORD }}
        run: |
          echo "$CERTIFICATE_BASE64" | base64 --decode > ios_certificate.p12
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import ios_certificate.p12 -k build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain


      - name: Install Provisioning Profile
        env:
          PROFILE_BASE64: ${{ secrets.IOS_ADHOC_PROFILE }}
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "$PROFILE_BASE64" | base64 --decode > ~/Library/MobileDevice/ProvisioningProfiles/profile.mobileprovision


      - name: Create exportOptions.plist
        run: |
          cat <<EOF > ios/exportOptions.plist
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>ad-hoc</string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>teamID</key>
              <string>${{ secrets.APPLE_TEAM_ID }}</string>
              <key>provisioningProfiles</key>
              <dict>
                  <key>com.lrg.riskconcierge</key>
                  <string>~/Library/MobileDevice/ProvisioningProfiles/profile.mobileprovision</string>
              </dict>
          </dict>
          </plist>
          EOF


      - name: Build IPA
        env:
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: |
          ENVFILE=../.env
          xcodebuild -workspace ios/react_native.xcworkspace \
                     -scheme react_native \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath build/react_native.xcarchive \
                     DEVELOPMENT_TEAM=$APPLE_TEAM_ID \
                     archive


      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
                     -archivePath build/react_native.xcarchive \
                     -exportOptionsPlist ios/exportOptions.plist \
                     -exportPath build


      - name: Upload IPA as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-release-ipa
          path: build/react_native.ipa
